Repository Estsoft-Udon/Udon_Community, pull requests merged in 2024-11, with the labels that each got.

#99 feat : 프론트 html 페이지 추가
  build.gradle
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/member.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/js/layout.js
  src/main/resources/static/js/member.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/layout.html
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/find_pw.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/signup.html
  src/main/resources/templates/member/success.html
  src/main/resources/templates/member/withdrawal.html
Labels: Feature

#135 Feature/create articles
  src/main/java/com/example/estsoft_udon_community/config/SecurityConfig.java
  src/main/java/com/example/estsoft_udon_community/controller/ArticlesController.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleDetailResponse.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/java/com/example/estsoft_udon_community/service/HashtagService.java
  src/main/java/com/example/estsoft_udon_community/service/LocationService.java
  src/main/java/com/example/estsoft_udon_community/util/SecurityUtil.java
  src/main/resources/static/js/common.js
  src/main/resources/static/js/index.js
  src/main/resources/templates/board/board_list.html
Labels: Feature

#134 Feature/view articles
  src/main/java/com/example/estsoft_udon_community/controller/ArticlesController.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/HashtagRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/resources/templates/board/board_list.html
Labels: Feature

#138 Feature/comment_crud
  build.gradle
  http/comments.http
  src/main/java/com/example/estsoft_udon_community/EstsoftUdonCommunityApplication.java
  src/main/java/com/example/estsoft_udon_community/config/JasyptConfigAES.java
  src/main/java/com/example/estsoft_udon_community/config/SecurityConfig.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/CommentsController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewBoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewCommentController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/dto/request/CommentsRequest.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsResponse.java
  src/main/java/com/example/estsoft_udon_community/entity/Comments.java
  src/main/java/com/example/estsoft_udon_community/entity/Users.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/CommentsLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/CommentsRepository.java
  src/main/java/com/example/estsoft_udon_community/security/CustomAuthenticationFailureHandler.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsService.java
  src/main/resources/application.properties
  src/main/resources/static/css/board.css
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board/board_detail.html
  src/main/resources/templates/layout/header.html
  src/main/resources/udon.md
Labels: Feature

#147 refactor : 게시글 리스트 지역 위치 이동 및 검색창 넓이 수정
  src/main/resources/static/css/board.css
  src/main/resources/templates/board/board_list.html
Labels: Refactor

#153 Feature/view articles
  src/main/java/com/example/estsoft_udon_community/controller/ArticlesController.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/repository/CommentsRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/HashtagRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/resources/static/js/boardList.js
  src/main/resources/templates/board/board_list.html
Labels: Feature

#154 Feature/article update
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/resources/static/css/board.css
  src/main/resources/static/js/board.js
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board/board_detail.html
  src/main/resources/templates/layout/header.html
Labels: Feature

#163 Fix: id 이름 변경으로 인한 오류 해결
  src/main/java/com/example/estsoft_udon_community/config/SecurityConfig.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/repository/LocationRepository.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/resources/static/js/board.js
  src/main/resources/static/js/common.js
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/signup.html
Labels: Fix

#164 Feature/article update
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/entity/Articles.java
  src/main/java/com/example/estsoft_udon_community/repository/LocationRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/java/com/example/estsoft_udon_community/service/LocationService.java
  src/main/resources/static/js/board.js
  src/main/resources/templates/board/board_detail.html
  src/main/resources/templates/board/board_edit.html
  src/main/resources/templates/member/edit_profile.html
Labels: Feature

#166 Feature/event calendar
  src/main/java/com/example/estsoft_udon_community/controller/EventController.java
  src/main/java/com/example/estsoft_udon_community/service/EventService.java
  src/main/resources/static/css/index.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: Feature

#165 Feature/view articles
  src/main/java/com/example/estsoft_udon_community/controller/ArticlesController.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/MainController.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/HashtagRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/resources/templates/board/board_list.html
Labels: Feature

#177 Feature/main page topuser
  src/main/java/com/example/estsoft_udon_community/controller/CommentsController.java
  src/main/java/com/example/estsoft_udon_community/controller/EventController.java
  src/main/java/com/example/estsoft_udon_community/controller/LikeController.java
  src/main/java/com/example/estsoft_udon_community/controller/MainController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewCommentController.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/CommentsLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/UsersRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/resources/static/js/board.js
  src/main/resources/static/js/comment.js
  src/main/resources/templates/board/board_detail.html
  src/main/resources/templates/index.html
Labels: Feature

#184 Feature/user details
  src/main/java/com/example/estsoft_udon_community/controller/UsersController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/repository/UsersRepository.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/resources/static/js/id_check.js
  src/main/resources/static/js/password_change.js
  src/main/resources/static/js/password_check.js
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/signup.html
Labels: Feature

#185 Feature/main page topuser
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/CommentsController.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/CommentsLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/resources/static/js/board.js
  src/main/resources/templates/admin/member/member_edit.html
  src/main/resources/templates/board/board_edit.html
  src/main/resources/templates/index.html
Labels: Feature

#197 Feature/event calendar
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminEventController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminEventViewController.java
  src/main/java/com/example/estsoft_udon_community/dto/response/EventResponse.java
  src/main/java/com/example/estsoft_udon_community/enums/EventType.java
  src/main/java/com/example/estsoft_udon_community/repository/EventRepository.java
  src/main/java/com/example/estsoft_udon_community/service/admin/AdminEventService.java
  src/main/resources/static/admin/css/reset.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/admin/event/event_edit.html
  src/main/resources/templates/admin/event/event_list.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
Labels: Feature

#196 Feature/add hashtag
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/entity/ArticleHashtagJoin.java
  src/main/java/com/example/estsoft_udon_community/entity/Articles.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticleHashtagJoinRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/LocationRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticleHashtagService.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/java/com/example/estsoft_udon_community/service/LocationService.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/resources/static/js/board.js
  src/main/resources/templates/board/board_detail.html
  src/main/resources/templates/board/board_edit.html
  src/main/resources/templates/member/edit_profile.html
  src/main/resources/templates/member/mypage.html
Labels: Feature, Fix

#204 Feature/admin_article
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminBoardViewController.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesRepository.java
  src/main/java/com/example/estsoft_udon_community/service/admin/AdminArticleService.java
  src/main/resources/templates/admin/board/board_list.html
Labels: Feature, Refactor

#201 Feature/add hashtag
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/resources/static/js/password_change.js
  src/main/resources/static/js/withdrawal.js
  src/main/resources/templates/board/board_list.html
  src/main/resources/templates/member/change_pw.html
  src/main/resources/templates/member/withdrawal.html
Labels: Feature

#212 게시판 관련 개선 및 기능추가
  src/main/java/com/example/estsoft_udon_community/controller/ArticlesController.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/MainController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesRepository.java
  src/main/java/com/example/estsoft_udon_community/repository/HashtagRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/java/com/example/estsoft_udon_community/service/HashtagService.java
  src/main/resources/templates/board/board_list.html
Labels: Feature, Fix, Refactor

#215 Feature/best comment
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/MainController.java
  src/main/java/com/example/estsoft_udon_community/controller/UsersController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewCommentController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleDetailResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleWithLikeResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsArticlesResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsWithLikeResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/EventResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/UsersResponse.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesLikeRepository.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/java/com/example/estsoft_udon_community/util/DateFormatUtil.java
  src/main/resources/static/css/board.css
  src/main/resources/static/js/withdrawal.js
  src/main/resources/templates/admin/member/member_list.html
  src/main/resources/templates/board/board_detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/member/withdrawal.html
Labels: Feature, Fix

#217 fix: 지역게시글에서 검색시 전체로 바뀌는점 수정
  src/main/resources/static/js/index.js
  src/main/resources/templates/board/board_list.html
Labels: Fix

#218 Feature/admin member
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminMemberController.java
  src/main/java/com/example/estsoft_udon_community/repository/UsersRepository.java
  src/main/java/com/example/estsoft_udon_community/service/admin/AdminMemberService.java
  src/main/resources/static/admin/css/calender.css
  src/main/resources/static/js/admin_member.js
  src/main/resources/templates/admin/member/member_list.html
Labels: Feature, Fix

#225 Feature/login fail
  http/comments.http
  src/main/java/com/example/estsoft_udon_community/config/JasyptConfigAES.java
  src/main/java/com/example/estsoft_udon_community/config/SecurityConfig.java
  src/main/java/com/example/estsoft_udon_community/controller/BoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/CommentsController.java
  src/main/java/com/example/estsoft_udon_community/controller/LikeController.java
  src/main/java/com/example/estsoft_udon_community/controller/MainController.java
  src/main/java/com/example/estsoft_udon_community/controller/UsersController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewBoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewCommentController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminBoardController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminBoardViewController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminEventController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminEventViewController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminMemberController.java
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminViewController.java
  src/main/java/com/example/estsoft_udon_community/dto/ToggleVisibilityRequest.java
  src/main/java/com/example/estsoft_udon_community/dto/request/AddArticleRequest.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleWithLikeResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/UsersResponse.java
  src/main/java/com/example/estsoft_udon_community/entity/ArticleHashtagJoin.java
  src/main/java/com/example/estsoft_udon_community/entity/Articles.java
  src/main/java/com/example/estsoft_udon_community/entity/Comments.java
  src/main/java/com/example/estsoft_udon_community/entity/Event.java
  src/main/java/com/example/estsoft_udon_community/entity/Location.java
  src/main/java/com/example/estsoft_udon_community/entity/Users.java
  src/main/java/com/example/estsoft_udon_community/enums/ArticleCategory.java
  src/main/java/com/example/estsoft_udon_community/enums/Grade.java
  src/main/java/com/example/estsoft_udon_community/repository/ArticlesRepository.java
  src/main/java/com/example/estsoft_udon_community/security/CustomAuthFailureHandler.java
  src/main/java/com/example/estsoft_udon_community/security/CustomAuthenticationFailureHandler.java
  src/main/java/com/example/estsoft_udon_community/security/UsersDetailService.java
  src/main/java/com/example/estsoft_udon_community/service/ArticleHashtagService.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsLikeService.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsService.java
  src/main/java/com/example/estsoft_udon_community/service/EventService.java
  src/main/java/com/example/estsoft_udon_community/service/LocationService.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/java/com/example/estsoft_udon_community/service/admin/AdminArticleService.java
  src/main/java/com/example/estsoft_udon_community/util/ModelUtil.java
  src/main/resources/static/css/member.css
  src/main/resources/templates/member/find_id.html
  src/main/resources/templates/member/find_pw.html
  src/main/resources/templates/member/login.html
Labels: Fix, Refactor, Remove, Rename

#227 feat: admin/board/board_list 에 '공개 여부'로 정렬 추가
  src/main/java/com/example/estsoft_udon_community/controller/admin/AdminBoardViewController.java
  src/main/resources/static/css/board.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/index.js
  src/main/resources/templates/admin/board/board_list.html
  src/main/resources/templates/index.html
  src/main/resources/udon.md
Labels: Feature

#229 Feature/fix header
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/enums/Grade.java
  src/main/resources/static/css/member.css
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/member/mypage.html
Labels: Feature, Fix

#234 fix : header에 로그인시 마이페이지 와 로그아웃만 보이기로 변경
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/edit_profile.html
Labels: Fix

#235 feat: 회원정보수정
  src/main/resources/static/js/edit_profile.js
  src/main/resources/templates/member/edit_profile.html
Labels: Feature

#238 fix: best_comment 로직 수정
  src/main/java/com/example/estsoft_udon_community/controller/ViewCommentController.java
Labels: Fix

#241 fix :getLoggerInUser() 로직 변경
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/service/ArticlesService.java
Labels: Fix, Refactor

#244 fix : 게시글 상세 내용 줄바꿈 처리 수정
  src/main/resources/static/css/board.css
Labels: Fix

#242 fix: checkId 함수 Promise추가
  src/main/resources/static/js/signup.js
Labels: Fix

#246 refactor: 게시판 표시 개선
  src/main/resources/templates/board/board_list.html
Labels: Refactor

#249 fix : 마이페이지 등급 관련 텍스트 수정
  src/main/resources/templates/member/mypage.html
Labels: Fix

#245 한 뚝배기 게시글 없을 때 글 노출
  src/main/java/com/example/estsoft_udon_community/dto/response/EventResponse.java
  src/main/resources/static/js/index.js
  src/main/resources/templates/admin/event/event_edit.html
  src/main/resources/templates/admin/event/event_list.html
  src/main/resources/templates/index.html
Labels: Refactor

#248 fix :getLoggerInUser() 를 직접적으로 사용하는 Users 들 모두 Id만 사용하도록 변경
  src/main/java/com/example/estsoft_udon_community/config/SecurityConfig.java
  src/main/java/com/example/estsoft_udon_community/controller/EventController.java
  src/main/java/com/example/estsoft_udon_community/controller/LikeController.java
  src/main/java/com/example/estsoft_udon_community/controller/UsersController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewCommentController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/service/CommentsService.java
  src/main/java/com/example/estsoft_udon_community/service/UsersService.java
  src/main/java/com/example/estsoft_udon_community/service/admin/AdminService.java
  src/main/java/com/example/estsoft_udon_community/util/SecurityUtil.java
  src/main/resources/udon.md
Labels: Fix, Refactor

#250 refactor : 캘린더 상세글 문단 그대로 노출
  src/main/resources/static/admin/css/reset.css
  src/main/resources/static/css/index.css
  src/main/resources/templates/admin/event/event_edit.html
  src/main/resources/templates/index.html
Labels: Refactor

#258 Feature/readme
  README.md
  docs/1.jpg
  docs/erd.png
  docs/figma_admin.jpg
  docs/figma_front.jpg
  docs/func1.png
  docs/func10.png
  docs/func2.png
  docs/func3.png
  docs/func4.png
  docs/func5.png
  docs/func6.png
  docs/func7.png
  docs/func8.png
  docs/func9.png
  docs/logo.png
  docs/logo_tran.png
  docs/mem1.jpg
  docs/mem2.jpg
  docs/mem3.png
  docs/mem4.jpg
  docs/mem5.png
  docs/udon.png
  docs/ui01.jpg
  docs/ui02.jpg
  docs/ui03.jpg
  docs/ui04.jpg
  docs/ui05.jpg
  docs/ui06.jpg
Labels: Docs

#256 Refactor/board edit
  src/main/java/com/example/estsoft_udon_community/service/admin/AdminService.java
  src/main/resources/templates/board/board_edit.html
  src/main/resources/templates/index.html
Labels: Fix, Refactor

#260 Fix/readme
  README.md
  docs/erd.png
  docs/func10.png
  docs/func9.png
  src/main/java/com/example/estsoft_udon_community/external/controller/FestivalDatasController.java
  src/main/java/com/example/estsoft_udon_community/external/service/FestivalDatasService.java
  src/main/resources/static/js/index.js
Labels: Docs

#262 docs : 역할, 코멘트, 추가 기능 구현 내용 추가, 문단 간격 수정
  README.md
Labels: Docs

#263 Feature/readme
  README.md
  docs/image.png
  src/main/resources/static/css/index.css
Labels: Docs

#265 fix: README 수정
  README.md
  src/main/java/com/example/estsoft_udon_community/controller/EventController.java
  src/main/java/com/example/estsoft_udon_community/controller/LikeController.java
  src/main/java/com/example/estsoft_udon_community/controller/ViewController.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleDetailResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/ArticleWithLikeResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsArticlesResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/CommentsWithLikeResponse.java
  src/main/java/com/example/estsoft_udon_community/dto/response/UsersResponse.java
Labels: Fix

#271 refactor : 게시판 리스트, 상세 반응형
  src/main/resources/static/css/board.css
Labels: Refactor
